Vagrant.configure("2") do |config|
    
  ### Nginx VM ###
    config.vm.define "nginx01" do |nginx01|
        nginx01.vm.box = "ubuntu/xenial64"
        nginx01.vm.hostname = "nginx01"
        nginx01.vm.network "private_network", ip: "192.168.60.11"
        nginx01.vm.provision "shell", inline: <<-SHELL
            apt update
            apt upgrade
            apt install nginx -y
            sudo systemctl restart nginx
        SHELL
    end    
end
  