Vagrant.configure("2") do |config|
    config.vm.define "db01" do |db01|
        db01.vm.box = "geerlingguy/centos7"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.15"
        db01.vm.provision "shell", inline: <<-SHELL
            yum update -y
            yum install epel-release -y
            yum install git mariadb-server -y
            systemctl start mariadb
            systemctl enable mariadb
        SHELL
    end
end
  