Vagrant.configure("2") do |config|
    
### RabbitMQ vm  ####
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "geerlingguy/centos7"
    rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", ip: "192.168.56.16"
        rmq01.vm.provision "shell", path: "rabbitmq.sh"  
    end   
end