NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 2

IP_NW = "192.168.56."
MASTER_IP_START = 1
NODE_IP_START = 2

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
  
    config.vm.box_check_update = false

    # Provision Master Nodes
    (1..NUM_MASTER_NODE).each do |i|
        config.vm.define "jenkins.master0#{i}" do |node|
          # Name shown in the GUI
          node.vm.provider "virtualbox" do |vb|
              vb.name = "jenkins.master0#{i}"
              vb.memory = 2048
              vb.cpus = 2
              vb.gui = true
          end
          node.vm.hostname = "jenkins.master0#{i}"
          node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
          node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
  
        #   node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
        #     s.args = ["enp0s8"]
        #   end
  
          node.vm.provision "setup-controller", type: "shell", :path => "controller_install.sh"
  
        end
    end
  
  
    # Provision Worker Nodes
    (1..NUM_WORKER_NODE).each do |i|
      config.vm.define "jenkins.node.0#{i}" do |node|
          node.vm.provider "virtualbox" do |vb|
              vb.name = "jenkins.node.0#{i}"
              vb.memory = 1024
              vb.cpus = 2
              vb.gui = true
          end
          node.vm.hostname = "jenkins.node.0#{i}"
          node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
          node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
  
        #   node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
        #     s.args = ["enp0s8"]
        #   end
  
          node.vm.provision "setup-agent", type: "shell", :path => "agent_install.sh"
      end
    end
  end